version: 2.0


orbs:
  browser-tools: circleci/browser-tools@x.y
jobs:

  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
        name: Check install
        command: |
          google-chrome --version
          chromedriver --version
      - run: mvn dependency:go-offline # gets the project dependencies 
      - run: mvn package

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
