version: 2.0

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run: mvn test

  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run: mvn dependency:go-offline # gets the project dependencies
      - run: mvn package

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
