version: 2.1


orbs:
  browser-tools: circleci/browser-tools@x.y
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
      - image: cimg/node:13.12-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
        name: Check install
        command: |
          google-chrome --version
          chromedriver --version
      - checkout
      - run: mvn dependency:go-offline # gets the project dependencies 
      - run: mvn package

workflows:
  buildmvn:
    jobs:
      - build
